WITH CTE AS (
select
TRY_TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TRY_TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TRY_TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
CASE 
WHEN DAYNAME(TRY_TO_TIMESTAMP(STARTED_AT)) in ('Sat','Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
{{ get_weather('STARTED_AT') }}
    END AS STATION_OF_YEAR
from
{{ source('demo','bike') }}
where STARTED_AT != 'started_at' and STARTED_AT != '"started_at"'
)
select 
*
from CTE